import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavProvider } from "../providers/NavProvider";
import PrimarySidebar from "@/components/ui/PrimarySidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/file.svg",
    shortcut: "/logo3.svg",
    apple: "/logo3.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <NavProvider>
        <body className="min-h-screen bg-background overflow-hidden w-full">
          <div className="main-cont flex h-full  w-full ">
            {children}
          </div>
        </body>
      </NavProvider>
    </html>
  );
}
